Add default location setting (merge from JiscRDSS fork)
artefactual/archivematica-storage-service pull request #212
Opened 2017-07-11 09:22 UTC by lower29

This merges changes from https://github.com/JiscRDSS/archivematica-storage-service/pull/8 and https://github.com/JiscRDSS/archivematica-storage-service/pull/11 into the Artefactual fork for issue #211.

Code is unchanged from @sevein's original commits - the only thing I've done is combine the two PRs and fix a minor typo in the location template.

2017-08-03 14:41 UTC, helenst commented
I've rebased this against the latest qa/1.x

2017-08-03 22:04 UTC, jrwdunham requested changes
I've played around with this and it works as I expect. I have a couple of change requests related to user and developer documentation. But in terms of functionality it looks good to me.

2017-08-03 22:04 UTC, jrwdunham commented on storage_service/locations/api/resources.py
> +    def default(self, request, **kwargs):
Is there a reason that you can not using the `_custom_endpoint` decorator? If not, then maybe you should for module-internal consistency. If yes, could you add a brief comment indicating why?

2017-08-03 22:04 UTC, jrwdunham commented on storage_service/locations/api/resources.py
> +    def hydrate_current_location(self, bundle):
I think this should have a docstring to reduce the amount of tastypie knowledge that is required to understand this functionality. Also, I think the `LOGGER.debug` calls should be to `.info` and `.warning` in production, no?

2017-08-03 22:04 UTC, jrwdunham commented on storage_service/locations/models/location.py
> +    # signal receivers unset_default_locaiton and set_default_location for
typo

2017-08-03 22:04 UTC, jrwdunham commented on storage_service/locations/forms.py
> +    default = forms.BooleanField(required=False)
Can this have a help string, e.g., like the "Enabled" attribute has "True if space can be accessed"? 

Speaking of which, it seems confusing that it's not "True if location can be accessed" at https://github.com/artefactual/archivematica-storage-service/blob/qa/0.x/storage_service/locations/models/location.py#L75, no?

2017-08-03 23:45 UTC, sevein commented on storage_service/locations/forms.py
> +    default = forms.BooleanField(required=False)
True but that'd need a new migration, right?

2017-08-03 23:46 UTC, sevein commented
Ok, I've made the changes suggested!

2017-08-04 12:44 UTC, helenst reviewed
I'm happy with this, nothing to add beyond what @jrwdunham has already pointed out.

2017-08-04 12:51 UTC, helenst requested changes

2017-08-04 12:51 UTC, helenst commented on storage_service/locations/forms.py
> +    default = forms.BooleanField(required=False, help=_l("Set as global default location for its purpose"))
This should be `label` rather than `help`

2017-08-04 15:24 UTC, sevein commented
I'll take a look when I'm back on Tuesday, unless you want to do it.

2017-08-04 16:04 UTC, helenst commented
@sevein no worries, I will sort it out! :)

2017-08-04 16:25 UTC, helenst approved these changes

2017-08-08 20:52 UTC, merged