WIP: Store package checksum to verify we have the expected package during fixity checks
artefactual/archivematica-storage-service pull request #639
Opened 2022-08-31 17:33 UTC by tw4l

This commit adds checksum and checksum_algorithm fields to the Package model, which are populated during AIP storage. These are then used during fixity checks to ensure that not only does the Bag validate, but we are validating the expected package.

This makes extracting and validating the Bag for newly stored compressed AIPs potentially unnecessary, which may have a nice side benefit of speeding up fixity checks considerably for compressed AIPs.

2022-09-07 16:05 UTC, scollazo requested changes

2022-09-07 16:05 UTC, scollazo commented on storage_service/common/utils.py
> +        if bag_file.startswith("tagmanifest"):
The spec says that [a bag may contain one or more tag manifest](https://www.rfc-editor.org/rfc/rfc8493.html#section-2.2.1), should we look for them following an order? (sha512, sha256, md5)?

2022-09-07 16:42 UTC, scollazo commented on storage_service/common/utils.py
> +        if bag_file.startswith("tagmanifest"):
Also, they should always end in ```.txt```

2022-09-07 18:09 UTC, tw4l commented on storage_service/common/utils.py
> +        if bag_file.startswith("tagmanifest"):
great catch, thank you!

2022-09-12 20:46 UTC, tw4l commented
Running the black box Automated Tests reveals an issue with reingest, which currently fails on this branch. Some log output:

```
```
archivematica-storage-service_1  | INFO      2022-09-12 16:42:38  locations.models.package:package:extract_file:1650:  Extracting file with: ['7z', 'x', '-bd', '-y', '-o/var/archivematica/storage_service/tmp53xl3qya', '/var/archivematica/sharedDirectory/www/AIPsStore/f0ab/2c9e/16f2/454d/b07b/7a97/91ae/5930/amauat-transfer_1663013929-f0ab2c9e-16f2-454d-b07b-7a9791ae5930.7z'] to /var/archivematica/storage_service/tmp53xl3qya/amauat-transfer_1663013929-f0ab2c9e-16f2-454d-b07b-7a9791ae5930
archivematica-storage-service_1  | DEBUG     2022-09-12 16:42:38  locations.models.package:package:start_reingest:2253:  Reingest: extracted to /var/archivematica/storage_service/tmp53xl3qya/amauat-transfer_1663013929-f0ab2c9e-16f2-454d-b07b-7a9791ae5930
archivematica-storage-service_1  | ERROR     2022-09-12 16:42:38  locations.models.package:package:check_fixity:2002:  Package checksum 1ccce54804393a5014b42f372d9233a4ce5f83edd556fb17b7260d5338c41a34 for package f0ab2c9e-16f2-454d-b07b-7a9791ae5930 did not validate against expected value 4d09bc1d38efb7e00c1f5a580bd4503818cb10e399dadf5ee4145b2ae29016a5	
```

Calling the /check_fixity/ endpoint for the same package succeeds, so I think it might be about the order of operations during reingest (unpacking before checking fixity). I will look into this closer tomorrow.,

2022-09-13 15:02 UTC, tw4l commented
Commit https://github.com/artefactual/archivematica-storage-service/pull/639/commits/c8442818d5d66c801f2f082d941768f9eec79e37 modifies `Package.start_reingest` to check a package's fixity prior to extracting it, which fixes reingest and causes the black box tests to once again pass.

I've checked elsewhere in the Storage Service where `Package.check_fixity()` is called and it seems that this was the only place that packages were extracted prior to running fixity, so I wouldn't expect to see this same side effect elsewhere.

2022-09-13 15:49 UTC, scollazo approved these changes

2022-09-13 22:45 UTC, tw4l commented
Rebased on latest `qa/0.x`

2022-09-15 18:48 UTC, merged